"Instrucions Pathogen
execute pathogen#infect()
filetype plugin indent on

"if you use fish shell 
set shell=/bin/bash

"mapping t key to <Leader>
let mapleader = ","

"Always open nerdtree (oprtional)
"autocmd vimenter * NERDTree

"Setting Molokai Color
colorscheme molokai
let g:molokai_original = 1
let g:rehash256 = 1
set background=dark

"Map Ctrl+t to open Nerd Tree
map <C-t> :NERDTreeToggle<CR>
"Map NerdtreeTabs
map <Leader>n <plug>NERDTreeTabsToggle<CR>
"Webdevicons
set encoding=utf8
set guifont=Droid\ Sans\ Mono\ for\ Powerline\ Plus\ Nerd\ File\ Types:h11

"YouCompleteMe
let g:ycm_seed_identifiers_with_syntax = 1

set number
"Applying best practices for drupal vim more information on https://drupal.org/node/29325
"Identation
set expandtab
set tabstop=2
set shiftwidth=2
set autoindent
set smartindent
"Syntax highlighting
if has("autocmd")
  " Drupal *.module and *.install files.
  augroup module
  autocmd BufRead,BufNewFile *.module set filetype=php
  autocmd BufRead,BufNewFile *.install set filetype=php
  autocmd BufRead,BufNewFile *.test set filetype=php
  autocmd BufRead,BufNewFile *.inc set filetype=php
  autocmd BufRead,BufNewFile *.profile set filetype=php
  autocmd BufRead,BufNewFile *.view set filetype=php
  autocmd BufRead,BufNewFile *.scss set filetype=css
  augroup END
endif

syntax on

"vim airline configurations
set laststatus=2
"in case to have powerline fonts
let g:airline_powerline_fonts = 1
"Set color terminal 256
set t_Co=256
